# Generated by Django 6.0.1 on 2026-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(default='sememail@gmail.com', max_length=150),
        ),
    ]
